### ISSUE TITLE
Write String checker output to corresponding files.

### ISSUE THREAD

**Issue by prateekiiest** [michelcaradec/string-checker-js#3]
Hi @michelcaradec ,
Thanks for this project. This is awesome and really helpful.

Wanted to know is there any feature by which instead of getting the output on the left bar, anyway it can be piped to some folder/file?

**Comment by michelcaradec** [comment]
Hello @prateekiiest , and thank you for your feedback.

This extension was mainly designed with IDE experience in mind, with interaction between the tree and the files.

One way to redirect the output would probably to refactor the [`StatsProvider`](https://github.com/michelcaradec/string-checker-js/blob/master/src/stats/statsProvider.ts) which collects information from the "low-level".
Even if possible, it would require some consequent effort, which I'm not able to provide at the moment, as I'm busy on other projects.

Sorry.

**Comment by prateekiiest** [comment]
Sure, no issues.
Thanks for the pointer BTW. I will have a look at the Statsprovider and check if it's a possibility.
Thanks again.
